baseURL = "https://Kaihchs118.github.io/kai_studio/"
languageCode = "zh-TW"
title = "KAI STUDIO"
theme = "PaperMod"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  showReadingTime = true
  showBreadCrumbs = true
  showPostNavLinks = true
  showCodeCopyButtons = true
  customCSS = ["css/custom.css"]
  showtoc = true
  tocopen = false
  background = true
  paginate = 6
  readingTimeWordsPerMinute = 1
  enableGitInfo = true
  enableSearch = true
  AutoThumbnailImage = true
  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 1
    keys = ["title", "content"]
  [params.utterances]
    enabled = true
    repo = "Kaihchs118/kai_studio"
    issueTerm = "pathname"
    label = "ğŸ’¬ ç•™è¨€å€"
    theme = "preferred-color-scheme"
  [params.assets]
    favicon = "img/demo1.png"
  [params.homeInfoParams]
    Title = "æ­¡è¿ä¾†åˆ°KAI STUDIO"
    Content = "å¾€ä¸‹æ»‘çœ‹çœ‹å§"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    identifier = "now"
    name = "ğŸ§­NOW"
    url = "/nav/now1/"
    weight = 2
  [[menu.main]]
    identifier = "tags"
    name = "ğŸ«æ¨™ç±¤"
    url = "/tags/"
    weight = 4
  [[menu.main]]
    identifier = "first-visit"
    name = "ğŸ¤¡æ­¡è¿"
    url = "/nav/First/"
    weight = 5
  [[menu.main]]
    identifier = "about"
    name = "ğŸ“é—œæ–¼æˆ‘"
    url = "/nav/about/"
    weight = 6