baseURL = "https://Kaihchs118.github.io/kai_studio/"
languageCode = "zh-TW"
title = "KAI STUDIO"
theme = "PaperMod"

[outputs]
  home = ["HTML", "RSS", "JSON"]


[params]
  showReadingTime = false
  showBreadCrumbs = true
  showPostNavLinks = true
  showCodeCopyButtons = true
  customCSS = ["css/custom.css"]
  # é–‹å•Ÿæœå°‹
  [params.search]
    enable = true
    provider = "lunr"

  [params.utterances]
    enabled = true
    repo = "Kaihchs118/kai_studio"   # ä½ çš„ repo
    issueTerm = "pathname"           # ä»¥ç¶²å€ä½œç‚º issue å°æ‡‰
    label = "ğŸ’¬ ç•™è¨€å€"
    theme = "preferred-color-scheme"

  [params.assets]
    favicon = "img/demo1.png"

  [params.homeInfoParams]
    Title = "æ­¡è¿ä¾†åˆ°KAI STUDIO"
    Content = "å¾€ä¸‹æ»‘çœ‹çœ‹å§"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
  identifier = "home"
  name = "é¦–é "
  url = "/"
  weight = 1

  [[menu.main]]
  identifier = "posts"
  name = "æ–‡ç« "
  url = "/posts/"
  weight = 2


  [[menu.main]]
  identifier = "tags"
  name = "æ¨™ç±¤"
  url = "/tags/"
  weight = 3


  [[menu.main]]
  identifier = "about"
  name = "é—œæ–¼æˆ‘"
  url = "/about/"
  weight = 4
  
  [[menu.main]]
  identifier = "first-visit"
  name = "æ–°æ‰‹æ‘"
  url = "/First/"
  weight = 5
