baseURL = "https://Kaihchs118.github.io/kai_studio/"
languageCode = "zh-TW"
title = "KAI STUDIO"
theme = "PaperMod"
[outputs]
  home = ["HTML", "RSS", "JSON"]
[params]
  showReadingTime = true  # å•Ÿç”¨é–±è®€æ™‚é–“é¡¯ç¤º
  showBreadCrumbs = true
  showPostNavLinks = true
  showCodeCopyButtons = true
  customCSS = ["css/custom.css"]
  showtoc = true
  tocopen = false
  background = true
  paginate = 6
  readingTimeWordsPerMinute = 1 # ä¿®æ­£ç‚ºæ¯åˆ†é˜ 5 å­—
  enableGitInfo = true
  [params.search]
    enable = true
    provider = "lunr"
  [params.utterances]
    enabled = true
    repo = "Kaihchs118/kai_studio"
    issueTerm = "pathname"
    label = "ğŸ’¬ ç•™è¨€å€"
    theme = "preferred-color-scheme"
  [params.assets]
    favicon = "img/demo1.png"
  [params.homeInfoParams]
    Title = "æ­¡è¿ä¾†åˆ°KAI STUDIO"
    Content = "å¾€ä¸‹æ»‘çœ‹çœ‹å§"
    
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[menu]
  [[menu.main]]
    identifier = "home"
    name = "é¦–é "
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "now"
    name = "NOW"
    url = "/nav/now1/"
    weight = 2
  [[menu.main]]
    identifier = "posts"
    name = "æ–‡ç« "
    url = "/posts/"
    weight = 3
  [[menu.main]]
    identifier = "tags"
    name = "æ¨™ç±¤"
    url = "/tags/"
    weight = 4
  [[menu.main]]
    identifier = "first-visit"
    name = "æ–°æ‰‹çœ‹é€™é‚Š"
    url = "/nav/First/"
    weight = 5
  [[menu.main]]
    identifier = "about"
    name = "é—œæ–¼æˆ‘"
    url = "/nav/about/"
    weight = 6